apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: externaldns-viewer
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - externaldns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.openshift.io
  resources:
  - externaldns/status
  verbs:
  - get
