apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: external-dns-operator
  name: external-dns-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: external-dns-operator
status:
  loadBalancer: {}
