apiVersion: externaldns.olm.openshift.io/v1beta1
kind: ExternalDNS
metadata:
  name: sample-aws
spec:
  domains:
  - filterType: Include
    matchType: Exact
    name: testextdnsoperator.apacshift.support
  provider:
    type: AWS
  source:
    # Source Type is route resource of OpenShift
    type: OpenShiftRoute
    # In case you have multiple ingress controllers you must specify ingress controller name in the routerName
    # so that the external dns will use the router canonical name correrponding to it to create a dns record.
    openshiftRouteOptions:
      routerName: default
  zones:
  - Z04015592QJX3EK1YYYYY
